# http://www.eidel.io/2017/07/10/dockerizing-django-uwsgi-postgres/

version: '3'

services:
  api:
    hostname: core
    container_name: core
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      TEST_DATABASE_URL: postgres://tiernan:password@postgres/walletcore
      KAKA_ENV: development
    ports:
      - "5000:80"
    # Mount local code to container
    volumes:
      - .:/app

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: walletcore
      POSTGRES_USER: tiernan
      POSTGRES_PASSWORD: password

